import "@/assets/blklight.scss";
import "katex/dist/katex.css";
import "react-tooltip/dist/react-tooltip.css";

import Head from "next/head";
import Layout from "../layouts/Layout";
import { ThemeProvider } from "next-themes";

import Barlow from "@/components/Fonts/Barlow";
import JetBrains from "@/components/Fonts/JetBrainsMono";
import IBMPlexSerif from "@/components/Fonts/IBMPlexSerif";

import { library, config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

import { fab } from "@fortawesome/free-brands-svg-icons";
import {
  faCircleHalfStroke,
  faCheckSquare,
  faCoffee,
  faSun,
  faMoon,
} from "@fortawesome/free-solid-svg-icons";

library.add(fab, faCheckSquare, faCoffee, faCircleHalfStroke, faSun, faMoon);

import { ClientReload } from "@/components/ClientReload";

const isDevelopment = process.env.NODE_ENV === "development";
const isSocket = process.env.SOCKET;

const App = ({ Component, pageProps }) => {
  return (
    <ThemeProvider enableSystem={true} attribute="class">
      <Head>
        <title>Ultimate Mercer - Testing NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isDevelopment && isSocket && <ClientReload />}
      <div
        className={`${Barlow.variable} ${JetBrains.variable} ${IBMPlexSerif.variable} font-sans`}
      >
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </div>
    </ThemeProvider>
  );
};

export default App;
